# Generated by Django 5.1.2 on 2025-10-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.module')),
            ],
            options={
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='content.qualification'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('MCQ_SINGLE', 'MCQ (Single)'), ('MCQ_MULTI', 'MCQ (Multiple)'), ('TRUE_FALSE', 'True/False'), ('SHORT', 'Short Answer'), ('LONG', 'Long/Subjective')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('skill_type', models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('APPLICATION', 'Application'), ('PROFESSIONAL', 'Professional')], max_length=15)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('marks', models.FloatField(default=1.0)),
                ('professional_marks', models.FloatField(default=0.0)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.chapter')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.module')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.paper')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.qualification')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('paper', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('qualification', 'name')},
        ),
    ]
