# Generated by Django 5.1.2 on 2025-10-29 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], default='STARTED', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_sec', models.IntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='questions',
            field=models.ManyToManyField(through='exams.AttemptItem', to='content.question'),
        ),
        migrations.CreateModel(
            name='ResumeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_events', to='exams.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('batches', models.ManyToManyField(blank=True, to='accounts.batch')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.scheduledtest'),
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('EXAM', 'Exam'), ('PRACTICE', 'Practice')], default='EXAM', max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.paper')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledtest',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.testtemplate'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.testtemplate'),
        ),
    ]
