# Generated by Django 5.1.2 on 2025-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptitem',
            name='manual_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptitem',
            name='reviewer_notes',
            field=models.TextField(blank=True),
        ),
    ]
