# Generated by Django 5.1.2 on 2025-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_attemptitem_manual_score_attemptitem_reviewer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtest',
            name='override_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
