# Generated by Django 5.1.2 on 2025-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_scheduledtest_override_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='device_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attempt',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='security_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scheduledtest',
            name='ip_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
