# Generated by Django 5.1.2 on 2025-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_attempt_device_hash_attempt_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='pause_total_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
